# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08cdc61f5f843a217a9b79fbd59d4be78a138928b31fff3bc9dc964ff3d003abcb49153773d5656b22d86231f79e2836c86f12478bc3ae62e4ae270137efce3c

test:
  secret_key_base: e2cfebcd473f51d5fcf6c0e7ea7e21ae96e7974dc9b1465dc2fd9130a121c4ed81e1d259f72d1f4bd20b579686b78a0fb80932c89482266ede5d7ff18e6e362a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
